### ISSUE TITLE
feeding a pet until it turned to a mount did not remove pet from avatar, did not remove pet from pets screen in app

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#510]
UUID: d904bd62-da08-416b-a816-ba797c9ee265

On the Android app, I hatched a Base Falcon pet, equipped it in my avatar, then fed it until it turned into a mount. 

However on the app, the pet did not disappear from my avatar, and did not disappear from my list of pets, although it did appear in my list of mounts. See the app screenshot below which was taken after I had turned the pet into a mount. I have NOT rehatched the pet, but the pet is appearing as if I had.

On the website, the pet is still showing in my avatar (which is incorrect), but it is not showing in my pets page (which is correct; see second screenshot), and the mount is showing in my mounts page (correct).

My data in the database reflects what I see on the website:

```
    "items": {
        "currentMount": "",
        "currentPet": "Falcon-Base",    // this should not be here!
        "mounts": {
            ...
            ...
            "Falcon-Base": true
        },
        "pets": {
            ...
            ...
            "Falcon-Base": -1,
        },
    ...
```

![screenshot_2016-04-16-21-51-23](https://cloud.githubusercontent.com/assets/1495809/14580819/e292d89e-041d-11e6-81e8-f86b19e4a0d4.png)

![screen shot 2016-04-16 at 10 01 47 pm](https://cloud.githubusercontent.com/assets/1495809/14580838/dc70bdd6-041e-11e6-9814-e9c63b46e32b.png)

I was able to replicate this with a Shade Falcon pet, except this time the pet WAS removed from my avatar on the website and in the database, and was also removed from my avatar on the app after I synced (but still appeared incorrectly in the app's Pet screen).

**Comment by Alys** [comment]
For the two falcon pets which I still have not rehatched, if I "use" them on the app, they DO appear on my avatar on the app and website. That's clearly a bug in the API - it allows me to equip a pet that I don't own. Pinging @paglias in case this isn't already fixed in API v3.

I'm not suggesting that this be fixed in API v2. :)

The bug in the app is that they're still showing in my pets screen even though they've been converted to mounts and not rehatched.

**Comment by paglias** [comment]
Hmm @vIiRuS are you using the `equip` operation? In this case it shouldn't happen in v2 either

**Comment by vIiRuS** [comment]
Yes, I'm using the equip operation for mounts and pets.

@Alys do the pets still appear after you use the sync function in the app? (and if they do, do they also still appear if you relaunch the app completely? )

**Comment by saraolson** [comment]
I just tested this, and while it does seem fixed, you have to force a refresh for the pet to actually go away so it seems the pet is still in your avatar when it's actually not.

**Comment by vIiRuS** [comment]
After checking this: The stable is updated correctly, so it is just the avatar that is not updated. A fix for this would be to check if the avatar currently has the pet that was fed equipped and if yes, remove the pet locally. It's not necessary to sync to the server for this since the server already does that action of unequipping automatically.
